version: '3.8'
services:
  webserver:
    build:
      context: .
      target: development
    image: inest-dev-image:latest
    ports:
      - 2002:2002
      - 2000:2000
    volumes:
      - ./:/app
    restart: unless-stopped
  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD='DB!@#'
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: always
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 'DB!@#'
    ports:
      - 2003:80
    restart: unless-stopped

volumes:
  database-data:
