server:
  port: 2000
  servlet:
    context-path: /

spring:
  security:
    oauth2:
      client:
        client-id:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:2001/auth/realms/inestKeycloak
          jwk-set-uri: http://localhost:2001/auth/realms/inestKeycloak/protocol/openid-connect/certs

keycloak:
  url: http://localhost:2001/auth
  realm: inestKeycloak
  client-id: client-app
  username: user1
  password: admin