server:
  port: 2000
  servlet:
    context-path: /

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/inest"
    username: inest
    password: 'DB!@#'

