spring:
  security:
    filter:
      order: 10
  web:
    locale: en

server:
  port: 2000
  servlet:
    context-path: /

jwt:
  issuer: https://inest.ink/auth/token
  secret: e_bW^+m#<ny~/xP-Wxw`h|YMj>*>GX
